name: CI-Security
on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest bandit pip-audit

      - name: Run unit tests
        run: pytest -q

      - name: Run Bandit (SAST)
        run: bandit -r . -f sarif -o bandit.sarif -ll -iii || true

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      - name: Dependency scan (pip-audit)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt -f json -o pip-audit.json || true
          else
            pip-audit -f json -o pip-audit.json || true
          fi

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: pip-audit.json
