name: CI-Security
on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install pytest "bandit==1.7.5" pip-audit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests (smoke)
        run: pytest -q tests/test_sanity.py || true

      - name: Run Bandit (SAST)
        run: bandit -r . -ll -iii || true

      - name: Dependency scan (pip-audit)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt || true
          else
            pip-audit || true
          fi

  codeql:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: python
      - uses: github/codeql-action/analyze@v3
