name: CI-Security
on:
  push: { branches: [ master ] }
  pull_request: { branches: [ master ] }

permissions:
  contents: read
  security-events: write
  actions: read
  checks: write

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install pytest "bandit==1.7.5" pip-audit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests (smoke)
        run: pytest -q tests/test_sanity.py || true

      - name: Run Bandit (SAST) -> SARIF
        run: |
          bandit -r . -f sarif -o bandit.sarif -ll -iii || true
          if [ ! -s bandit.sarif ]; then
            echo '{"version":"2.1.0","runs":[]}' > bandit.sarif
          fi

      - name: Upload Bandit SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: bandit.sarif

      - name: Dependency scan (pip-audit)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit -r requirements.txt -f json -o pip-audit.json || true
          else
            pip-audit -f json -o pip-audit.json || true
          fi

      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit.sarif
            pip-audit.json
